# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=255)),
                ('box_author', models.CharField(max_length=255)),
                ('box_url', models.CharField(max_length=2500)),
                ('box_os', models.CharField(max_length=250)),
                ('box_checksum', models.CharField(max_length=512)),
                ('box_builders', models.CharField(max_length=100)),
            ],
        ),
    ]
